export const ROOM_TYPE_PUBLIC = 0;
export const ROOM_TYPE_PRIVATE = 1;

export const EVENT_ACTION = 'ACTION';

export const EVENT_CREATE_ROOM = 'CREATE_ROOM';
export const EVENT_CHANGE_ROOM = 'CHANGE_ROOM';
export const EVENT_JOIN_ROOM = 'JOIN_ROOM';
export const EVENT_CREATE_PRIVATE_ROOM = 'CREATE_PRIVATE_ROOM';

export const EVENT_NEW_MESSAGE = 'NEW_MESSAGE';
